### ISSUE TITLE
Network connection issue

### ISSUE THREAD

**Issue by phodina** [flathub/com.microsoft.Teams#66]
Hi,
I'd like to report issue with MS Teams running in Flatpak. When I launch the Flatpak application the MS Teams GUI starts and asks for my email. After submitting I get this wierd screen with the error msg: "We couldn't connect to the Internet. Try checking your connection"

Therefore I ran the following where I can see that I can connect to the `https://gooogle.com`.

Any idea what to do to make it work?
```
$ flatpak run  --command=sh --devel com.microsoft.Teams

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/cylon2p0/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

[📦 com.microsoft.Teams ~]$ wget https://google.com
--2021-07-16 07:41:05--  https://google.com/
Resolving google.com (google.com)... 216.58.201.78, 2a00:1450:4014:80d::200e
Connecting to google.com (google.com)|216.58.201.78|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.google.com/ [following]
--2021-07-16 07:41:05--  https://www.google.com/
Resolving www.google.com (www.google.com)... 172.217.23.196, 2a00:1450:4014:80c::2004
Connecting to www.google.com (www.google.com)|172.217.23.196|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://consent.google.com/ml?continue=https://www.google.com/&gl=CZ&m=0&pc=shp&hl=cs&src=1 [following]
--2021-07-16 07:41:05--  https://consent.google.com/ml?continue=https://www.google.com/&gl=CZ&m=0&pc=shp&hl=cs&src=1
Resolving consent.google.com (consent.google.com)... 172.217.23.206, 2a00:1450:4014:80c::200e
Connecting to consent.google.com (consent.google.com)|172.217.23.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                   [ <=>                                                                              ]  10.27K  --.-KB/s    in 0.003s  

2021-07-16 07:41:05 (3.11 MB/s) - ‘index.html’ saved [10521]

[📦 com.microsoft.Teams ~]$ teams 
Overriding TZ to Europe/Prague
[4 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/teams/teams --type=zygote
Error while parsing hooks JSON. Error: "ENOENT: no such file or directory, open '/home/cylon2p0/.var/app/com.microsoft.Teams/config/Microsoft/Microsoft Teams/hooks.json'"
(node:4) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:4) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:4) UnhandledPromiseRejectionWarning: Error: net::ERR_CERT_AUTHORITY_INVALID
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6411)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[📦 com.microsoft.Teams ~]$ teams -v
Overriding TZ to Europe/Prague
[225 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/teams/teams --type=zygote --v
Error while parsing hooks JSON. Error: "ENOENT: no such file or directory, open '/home/cylon2p0/.var/app/com.microsoft.Teams/config/Microsoft/Microsoft Teams/hooks.json'"
(node:225) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:225) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:225) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
^C^C
[📦 com.microsoft.Teams ~]$ teams --version
Overriding TZ to Europe/Prague
[354 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/extra/teams/teams --type=zygote
Error while parsing hooks JSON. Error: "ENOENT: no such file or directory, open '/home/cylon2p0/.var/app/com.microsoft.Teams/config/Microsoft/Microsoft Teams/hooks.json'"
(node:354) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:354) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:354) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
^C^C

```
![Network error](https://i.imgur.com/4VgRs8C.png)

**Comment by enricotagliavini** [comment]
Same error for me

**Comment by enricotagliavini** [comment]
Looks like a sandboxing problem, DNS is broken for me

```
$ flatpak run  --command=sh  com.microsoft.Teams
[📦 com.microsoft.Teams ~]$ curl https://odc.officeapps.live.com/odc/v2.1/federationprovider
curl: (6) Could not resolve host: odc.officeapps.live.com
[📦 com.microsoft.Teams ~]$ curl ''https://www.google.com
curl: (6) Could not resolve host: www.google.com
```

Since this is a different issue, I'll report it separately, sorry for the noise

**Comment by phodina** [comment]
No problem. I've managed to get Teams working in the meantime as chromium web application as I need it for my day job and I'm also attempting to port it as a native Guix package.

**Comment by kdtsh** [comment]
@phodina did you ever find a solution to this?

I have found a similar issue. On investigation, I have found that my organisation's certificate is not trusted - i.e. in the environment given by `flatpak run --command=sh --devel com.microsoft.Teams`, the command `wget https://<my-organisation>.com` yields "ERROR: The certificate of '<my-organisation>.com' is not trusted [...] doesn't have a known issuer". If you try to wget the address of your organisation do you get a similar error?

(Let me know how you go with packaging it in Guix natively! I have been trying to do the same and have been running into shared library issues - specifically I can now get the teams binary to run, but the Electron app fails as it cannot find libstdc++.)

N.B. https://issues.guix.gnu.org/49957 may be related

**Comment by phodina** [comment]
@kdtsh  thanks for the suggestion.

I currently use it as Nix package.

The chromium version also works, though I haven't found exactly what to do in order to run it on wayland with screenshare enabled as  described here https://uwot.eu/blog/microsoft-teams-on-fedora-and-wayland-with-screenshare/

Therefore I don't use flatpak any more.

There is a unfinished PR on Nonguix channel https://gitlab.com/nonguix/nonguix/-/merge_requests/126.
