### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [flathub/com.microsoft.Teams#73]
Hi!

For a while, I'm getting just a blank white screen when I launch Microsoft Teams from a flatpak instead of usual login screen.
Screenshot:
![image](https://user-images.githubusercontent.com/7355383/130434936-be0b0254-13ec-44e8-a5c7-db1b8d3903df.png)

In command-line, when I run `flatpak run co.microsoft.Teams`, I get the following:
```
Overriding TZ to Europe/Minsk
Error while parsing hooks JSON. Error: "ENOENT: no such file or directory, open '/home/zamazan4ik/.var/app/com.microsoft.Teams/config/Microsoft/Microsoft Teams/hooks.json'"
(node:2) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 ecsSettingsUpdated listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:2) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 appInitialized listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:2) UnhandledPromiseRejectionWarning: Error: LocalStorageService: key or value not defined
    at m.<anonymous> (/app/extra/teams/resources/app.asar/main.bundle.js:1:375928)
    at Generator.next (<anonymous>)
    at /app/extra/teams/resources/app.asar/main.bundle.js:1:374186
    at new Promise (<anonymous>)
    at i (/app/extra/teams/resources/app.asar/main.bundle.js:1:373931)
    at m.setValue (/app/extra/teams/resources/app.asar/main.bundle.js:1:375870)
    at t.AppLevel.set (/app/extra/teams/resources/app.asar/main.bundle.js:16:667207)
    at t.AppLevel.get (/app/extra/teams/resources/app.asar/main.bundle.js:16:667165)
    at /app/extra/teams/resources/app.asar/main.bundle.js:16:673433
    at Array.reduce (<anonymous>)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

My environment:
OS: Fedora 34
Flatpak: 1.10.2
Microsoft Teams: the latest published in Flathub

If you need any additional information - just ping me and I'll try to help

**Comment by meissnol** [comment]
Have the exact same problem on manjaro, but not using flatpak, istalled it from the AUR:
Manjaro-Version: 21.2.4
Teams: 1.4.00.26453-1

**Comment by SirRFI** [comment]
Similar problem. The app is either invisible or just blank window. As I later figured out, it's not just Flatpak. Fedora uses Wayland by default, switching to X11 helps.

![image](https://user-images.githubusercontent.com/32642697/156937776-f517eade-0b7a-4197-8b32-6a235b212ba0.png)

**Comment by meissnol** [comment]
I use X11 all the time. For me it helped to switch from the AUR package to the flatpak...

**Comment by pprado** [comment]
I'm using rhel 8 with flatpak and having the same problem.

**Comment by SiddharthPant** [comment]
I am on fedora 37 and this happens both with flathub and with the official RPM version.
Doing `flatpak run com.microsoft.Teams` displays error message that canberra-gtk-module and pk-gtk-module are missing. So to me it looks like the base Teams package is missing some required parameter which is letting it not detect these libraries since both of them already exist in Fedora 37.
